export const FETCH_PANORAMAS_START = 'FETCH_PANORAMAS_START';
export const FETCH_PANORAMAS_SUCCESS = 'FETCH_PANORAMAS_SUCCESS';
export const FETCH_PANORAMAS_FAIL = 'FETCH_PANORAMAS_FAIL';
export const CHOOSE_PANORAMA = 'CHOOSE_PANORAMA';
